# Generated by Django 2.2.5 on 2019-10-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='routen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(blank=True, max_length=300, null=True)),
                ('mon', models.CharField(blank=True, max_length=300, null=True)),
                ('tue', models.CharField(blank=True, max_length=300, null=True)),
                ('wed', models.CharField(blank=True, max_length=300, null=True)),
                ('thu', models.CharField(blank=True, max_length=300, null=True)),
                ('fri', models.CharField(blank=True, max_length=300, null=True)),
                ('sat', models.CharField(blank=True, max_length=300, null=True)),
                ('sun', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
