# Generated by Django 2.2.5 on 2019-10-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(blank=True, max_length=3000, null=True)),
            ],
        ),
    ]
