# Generated by Django 2.2.5 on 2019-10-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(blank=True, null=True, upload_to='')),
                ('cname', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
