# Generated by Django 2.2.5 on 2019-10-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0004_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=3000, null=True)),
                ('ph1', models.CharField(blank=True, max_length=20, null=True)),
                ('ph2', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
